/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#76b900',
        'primary-dark': '#5a8d00',
        'accent-pale': '#bff230',
        canvas: '#ffffff',
        'surface-dark': '#000000',
        'surface-soft': '#f7f7f7',
        'surface-elevated': '#1a1a1a',
        hairline: '#cccccc',
        'hairline-strong': '#5e5e5e',
        ink: '#000000',
        body: '#1a1a1a',
        mute: '#757575',
        stone: '#898989',
        ash: '#a7a7a7',
        'on-dark': '#ffffff',
        'on-dark-mute': 'rgba(255,255,255,0.7)',
        error: '#e52020',
        'error-deep': '#650b0b',
        warning: '#df6500',
        success: '#3f8500',
        'link-blue': '#0046a4',
      },
      borderRadius: {
        none: '0px',
        xs: '1px',
        sm: '2px',
        full: '9999px',
        DEFAULT: '2px',
      },
      fontFamily: {
        sans: ['Inter', 'Arial', 'Helvetica', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.25', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-xl': ['24px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-lg': ['22px', { lineHeight: '1.75', fontWeight: '400' }],
        'heading-md': ['20px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-sm': ['18px', { lineHeight: '1.4', fontWeight: '700' }],
        'card-title': ['17px', { lineHeight: '1.47', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'body-sm': ['15px', { lineHeight: '1.67', fontWeight: '400' }],
        'caption-md': ['14px', { lineHeight: '1.43', fontWeight: '700' }],
        'caption-sm': ['12px', { lineHeight: '1.25', fontWeight: '400' }],
        'caption-xs': ['11px', { lineHeight: '1', fontWeight: '700' }],
        'utility-xs': ['10px', { lineHeight: '1.5', fontWeight: '700' }],
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '64px',
      },
      boxShadow: {
        sticky: '0 0 5px 0 rgba(0,0,0,0.3)',
        none: 'none',
      },
    },
  },
  plugins: [],
}
