/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#76b900',
        'primary-dark': '#5a8d00',
        'accent-pale': '#a8d840',
        canvas: '#fafaf8',
        'surface-dark': '#0d0d0d',
        'surface-soft': '#f5f4f2',
        'surface-elevated': '#161616',
        hairline: '#dedad4',
        'hairline-strong': '#262626',
        ink: '#1c1a18',
        body: '#2a2826',
        mute: '#6b6764',
        stone: '#7a7673',
        ash: '#9e9a93',
        'on-dark': '#e0e0e0',
        'on-dark-mute': 'rgba(224,224,224,0.6)',
        error: '#c94040',
        'error-deep': '#5a1a1a',
        warning: '#c06010',
        success: '#4e8e18',
        'link-blue': '#3a70b8',
      },
      borderRadius: {
        none: '0px',
        xs: '2px',
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '20px',
        '2xl': '24px',
        full: '9999px',
        DEFAULT: '10px',
      },
      fontFamily: {
        sans: ['Inter', 'Arial', 'Helvetica', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.25', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-xl': ['24px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-lg': ['22px', { lineHeight: '1.75', fontWeight: '400' }],
        'heading-md': ['20px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-sm': ['18px', { lineHeight: '1.4', fontWeight: '700' }],
        'card-title': ['17px', { lineHeight: '1.47', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'body-sm': ['15px', { lineHeight: '1.67', fontWeight: '400' }],
        'caption-md': ['14px', { lineHeight: '1.43', fontWeight: '700' }],
        'caption-sm': ['12px', { lineHeight: '1.25', fontWeight: '400' }],
        'caption-xs': ['11px', { lineHeight: '1', fontWeight: '700' }],
        'utility-xs': ['10px', { lineHeight: '1.5', fontWeight: '700' }],
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '64px',
      },
      boxShadow: {
        sticky: '0 0 5px 0 rgba(0,0,0,0.3)',
        none: 'none',
      },
    },
  },
  plugins: [],
}
