// ─── Cycle Type Definitions ───────────────────────────────────────────────────

export const CYCLE_TYPES = {
  cut: {
    id: 'cut',
    label: 'Cut',
    emoji: '🔻',
    description: 'Perda de gordura',
    calorieAdjust: -500,
  },
  cut_aggressive: {
    id: 'cut_aggressive',
    label: 'Cut Agressivo',
    emoji: '🔻🔻',
    description: 'Perda de gordura acelerada',
    calorieAdjust: -750,
  },
  bulk: {
    id: 'bulk',
    label: 'Bulk',
    emoji: '🔺',
    description: 'Ganho de massa limpa',
    calorieAdjust: 500,
  },
  bulk_lean: {
    id: 'bulk_lean',
    label: 'Bulk Limpo',
    emoji: '🔺',
    description: 'Ganho de massa com controle de gordura',
    calorieAdjust: 300,
  },
  maintenance: {
    id: 'maintenance',
    label: 'Manutenção',
    emoji: '⚖️',
    description: 'Manter peso e composição atual',
    calorieAdjust: 0,
  },
  strength: {
    id: 'strength',
    label: 'Força',
    emoji: '💪',
    description: 'Maximizar ganhos de força',
    calorieAdjust: 200,
  },
  conditioning: {
    id: 'conditioning',
    label: 'Condicionamento',
    emoji: '🏃',
    description: 'Melhorar capacidade cardiovascular',
    calorieAdjust: 0,
  },
  recomposition: {
    id: 'recomposition',
    label: 'Recomposição',
    emoji: '🔄',
    description: 'Perder gordura e ganhar músculo simultaneamente',
    calorieAdjust: 0,
  },
  general_health: {
    id: 'general_health',
    label: 'Saúde Geral',
    emoji: '🧘',
    description: 'Foco em bem-estar e saúde geral',
    calorieAdjust: 0,
  },
  custom: {
    id: 'custom',
    label: 'Personalizado',
    emoji: '✏️',
    description: 'Metas e macros completamente customizáveis',
    calorieAdjust: 0,
  },
}

// ─── Macro Formulas ───────────────────────────────────────────────────────────
// protein_g_per_kg: grams of protein per kg of bodyweight
// fat_g_per_kg: grams of fat per kg of bodyweight (null = derive from carb_pct)
// carb_pct: percentage of total calories from carbs (null = fill remainder after protein + fat)
// carb_fill: if true, carbs fill remaining calories after protein + fat are set

export const MACRO_FORMULAS = {
  cut: {
    protein_g_per_kg: 2.2,
    fat_g_per_kg: 0.8,
    carb_pct: null,
    carb_fill: true,
  },
  cut_aggressive: {
    protein_g_per_kg: 2.4,
    fat_g_per_kg: 0.7,
    carb_pct: null,
    carb_fill: true,
  },
  bulk: {
    protein_g_per_kg: 1.8,
    fat_g_per_kg: null,
    carb_pct: 50,
    carb_fill: false,
  },
  bulk_lean: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: null,
    carb_pct: 45,
    carb_fill: false,
  },
  maintenance: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: 0.9,
    carb_pct: null,
    carb_fill: true,
  },
  strength: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: null,
    carb_pct: 45,
    carb_fill: false,
  },
  conditioning: {
    protein_g_per_kg: 1.8,
    fat_g_per_kg: null,
    carb_pct: 55,
    carb_fill: false,
  },
  recomposition: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: 0.9,
    carb_pct: null,
    carb_fill: true,
  },
  general_health: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: 0.9,
    carb_pct: null,
    carb_fill: true,
  },
  custom: {
    protein_g_per_kg: 2.0,
    fat_g_per_kg: 0.9,
    carb_pct: null,
    carb_fill: true,
  },
}

// ─── Activity Level Multipliers ───────────────────────────────────────────────

export const ACTIVITY_LEVELS = {
  sedentary: {
    id: 'sedentary',
    label: 'Sedentário',
    description: 'Pouco ou nenhum exercício',
    multiplier: 1.2,
  },
  light: {
    id: 'light',
    label: 'Levemente ativo',
    description: 'Exercício leve 1-3 dias/semana',
    multiplier: 1.375,
  },
  moderate: {
    id: 'moderate',
    label: 'Moderadamente ativo',
    description: 'Exercício moderado 3-5 dias/semana',
    multiplier: 1.55,
  },
  active: {
    id: 'active',
    label: 'Muito ativo',
    description: 'Exercício intenso 6-7 dias/semana',
    multiplier: 1.725,
  },
  very_active: {
    id: 'very_active',
    label: 'Extremamente ativo',
    description: 'Exercício muito intenso, trabalho físico diário',
    multiplier: 1.9,
  },
}

// ─── Default Card Layouts Per Cycle ──────────────────────────────────────────

export const DEFAULT_LAYOUTS_BY_CYCLE = {
  cut: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_water',          size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_calories',       size: 'small', order: 3 },
    { id: 'card_weight',         size: 'small', order: 4 },
    { id: 'card_streak',         size: 'small', order: 5 },
    { id: 'card_rules_today',    size: 'small', order: 6 },
    { id: 'card_fasting_timer',  size: 'large', order: 7 },
    { id: 'card_today_timeline', size: 'large', order: 8 },
    { id: 'card_sleep',          size: 'small', order: 9 },
    { id: 'card_wod_today',      size: 'large', order: 10 },
    { id: 'card_workout_streak', size: 'small', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_score_hero',     size: 'large', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  cut_aggressive: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_calories',       size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_water',          size: 'small', order: 3 },
    { id: 'card_weight',         size: 'small', order: 4 },
    { id: 'card_fasting_timer',  size: 'large', order: 5 },
    { id: 'card_rules_today',    size: 'small', order: 6 },
    { id: 'card_streak',         size: 'small', order: 7 },
    { id: 'card_sleep',          size: 'small', order: 8 },
    { id: 'card_today_timeline', size: 'large', order: 9 },
    { id: 'card_wod_today',      size: 'large', order: 10 },
    { id: 'card_workout_streak', size: 'small', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_score_hero',     size: 'large', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  bulk: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_calories',       size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_wod_today',      size: 'large', order: 3 },
    { id: 'card_workout_streak', size: 'small', order: 4 },
    { id: 'card_weight',         size: 'small', order: 5 },
    { id: 'card_water',          size: 'small', order: 6 },
    { id: 'card_sleep',          size: 'small', order: 7 },
    { id: 'card_supplements',    size: 'small', order: 8 },
    { id: 'card_score_hero',     size: 'large', order: 9 },
    { id: 'card_today_timeline', size: 'large', order: 10 },
    { id: 'card_streak',         size: 'small', order: 11 },
    { id: 'card_rules_today',    size: 'small', order: 12 },
    { id: 'card_next_meal',      size: 'small', order: 13 },
    { id: 'card_fasting_timer',  size: 'large', order: 14 },
  ],
  bulk_lean: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_calories',       size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_wod_today',      size: 'large', order: 3 },
    { id: 'card_workout_streak', size: 'small', order: 4 },
    { id: 'card_weight',         size: 'small', order: 5 },
    { id: 'card_water',          size: 'small', order: 6 },
    { id: 'card_sleep',          size: 'small', order: 7 },
    { id: 'card_fasting_timer',  size: 'large', order: 8 },
    { id: 'card_score_hero',     size: 'large', order: 9 },
    { id: 'card_today_timeline', size: 'large', order: 10 },
    { id: 'card_streak',         size: 'small', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_rules_today',    size: 'small', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  maintenance: [
    { id: 'card_score_hero',     size: 'large', order: 0 },
    { id: 'card_water',          size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_sleep',          size: 'small', order: 3 },
    { id: 'card_weight',         size: 'small', order: 4 },
    { id: 'card_calories',       size: 'small', order: 5 },
    { id: 'card_streak',         size: 'small', order: 6 },
    { id: 'card_today_timeline', size: 'large', order: 7 },
    { id: 'card_wod_today',      size: 'large', order: 8 },
    { id: 'card_fasting_timer',  size: 'large', order: 9 },
    { id: 'card_cycle_status',   size: 'large', order: 10 },
    { id: 'card_supplements',    size: 'small', order: 11 },
    { id: 'card_rules_today',    size: 'small', order: 12 },
    { id: 'card_next_meal',      size: 'small', order: 13 },
    { id: 'card_workout_streak', size: 'small', order: 14 },
  ],
  strength: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_wod_today',      size: 'large', order: 1 },
    { id: 'card_workout_streak', size: 'small', order: 2 },
    { id: 'card_protein',        size: 'small', order: 3 },
    { id: 'card_calories',       size: 'small', order: 4 },
    { id: 'card_water',          size: 'small', order: 5 },
    { id: 'card_weight',         size: 'small', order: 6 },
    { id: 'card_sleep',          size: 'small', order: 7 },
    { id: 'card_score_hero',     size: 'large', order: 8 },
    { id: 'card_today_timeline', size: 'large', order: 9 },
    { id: 'card_streak',         size: 'small', order: 10 },
    { id: 'card_supplements',    size: 'small', order: 11 },
    { id: 'card_rules_today',    size: 'small', order: 12 },
    { id: 'card_fasting_timer',  size: 'large', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  conditioning: [
    { id: 'card_wod_today',      size: 'large', order: 0 },
    { id: 'card_workout_streak', size: 'small', order: 1 },
    { id: 'card_water',          size: 'small', order: 2 },
    { id: 'card_calories',       size: 'small', order: 3 },
    { id: 'card_protein',        size: 'small', order: 4 },
    { id: 'card_cycle_status',   size: 'large', order: 5 },
    { id: 'card_sleep',          size: 'small', order: 6 },
    { id: 'card_score_hero',     size: 'large', order: 7 },
    { id: 'card_today_timeline', size: 'large', order: 8 },
    { id: 'card_streak',         size: 'small', order: 9 },
    { id: 'card_weight',         size: 'small', order: 10 },
    { id: 'card_fasting_timer',  size: 'large', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_rules_today',    size: 'small', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  recomposition: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_protein',        size: 'small', order: 1 },
    { id: 'card_calories',       size: 'small', order: 2 },
    { id: 'card_water',          size: 'small', order: 3 },
    { id: 'card_weight',         size: 'small', order: 4 },
    { id: 'card_wod_today',      size: 'large', order: 5 },
    { id: 'card_workout_streak', size: 'small', order: 6 },
    { id: 'card_sleep',          size: 'small', order: 7 },
    { id: 'card_fasting_timer',  size: 'large', order: 8 },
    { id: 'card_score_hero',     size: 'large', order: 9 },
    { id: 'card_today_timeline', size: 'large', order: 10 },
    { id: 'card_streak',         size: 'small', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_rules_today',    size: 'small', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  general_health: [
    { id: 'card_score_hero',     size: 'large', order: 0 },
    { id: 'card_water',          size: 'small', order: 1 },
    { id: 'card_sleep',          size: 'small', order: 2 },
    { id: 'card_streak',         size: 'small', order: 3 },
    { id: 'card_rules_today',    size: 'small', order: 4 },
    { id: 'card_today_timeline', size: 'large', order: 5 },
    { id: 'card_protein',        size: 'small', order: 6 },
    { id: 'card_calories',       size: 'small', order: 7 },
    { id: 'card_weight',         size: 'small', order: 8 },
    { id: 'card_supplements',    size: 'small', order: 9 },
    { id: 'card_fasting_timer',  size: 'large', order: 10 },
    { id: 'card_wod_today',      size: 'large', order: 11 },
    { id: 'card_workout_streak', size: 'small', order: 12 },
    { id: 'card_cycle_status',   size: 'large', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  custom: [
    { id: 'card_cycle_status',   size: 'large', order: 0 },
    { id: 'card_water',          size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_calories',       size: 'small', order: 3 },
    { id: 'card_sleep',          size: 'small', order: 4 },
    { id: 'card_score_hero',     size: 'large', order: 5 },
    { id: 'card_today_timeline', size: 'large', order: 6 },
    { id: 'card_wod_today',      size: 'large', order: 7 },
    { id: 'card_weight',         size: 'small', order: 8 },
    { id: 'card_workout_streak', size: 'small', order: 9 },
    { id: 'card_streak',         size: 'small', order: 10 },
    { id: 'card_fasting_timer',  size: 'large', order: 11 },
    { id: 'card_supplements',    size: 'small', order: 12 },
    { id: 'card_rules_today',    size: 'small', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
  // No active cycle
  default: [
    { id: 'card_fasting_timer',  size: 'large', order: 0 },
    { id: 'card_water',          size: 'small', order: 1 },
    { id: 'card_protein',        size: 'small', order: 2 },
    { id: 'card_sleep',          size: 'small', order: 3 },
    { id: 'card_streak',         size: 'small', order: 4 },
    { id: 'card_score_hero',     size: 'large', order: 5 },
    { id: 'card_today_timeline', size: 'large', order: 6 },
    { id: 'card_weight',         size: 'small', order: 7 },
    { id: 'card_calories',       size: 'small', order: 8 },
    { id: 'card_wod_today',      size: 'large', order: 9 },
    { id: 'card_workout_streak', size: 'small', order: 10 },
    { id: 'card_supplements',    size: 'small', order: 11 },
    { id: 'card_rules_today',    size: 'small', order: 12 },
    { id: 'card_cycle_status',   size: 'large', order: 13 },
    { id: 'card_next_meal',      size: 'small', order: 14 },
  ],
}

// ─── Predefined Cycle Templates ───────────────────────────────────────────────

export const PREDEFINED_CYCLE_TEMPLATES = [
  {
    id: 'cut_8w',
    name: 'Cut 8 semanas — Iniciante',
    type: 'cut',
    duration_weeks: 8,
    description: 'Protocolo de perda de gordura para iniciantes com déficit calórico moderado.',
    active_rules: [
      'Déficit calórico diário de ~500 kcal',
      'Proteína mínima de 2.2g por kg',
      'Treinar pelo menos 4x por semana',
      'Dormir 7-9h por noite',
      'Beber 35ml de água por kg corporal',
    ],
    custom_goals: {
      deficit_kcal: 500,
      training_days_per_week: 4,
      cardio_sessions_per_week: 2,
    },
  },
  {
    id: 'bulk_12w',
    name: 'Bulk limpo 12 semanas',
    type: 'bulk_lean',
    duration_weeks: 12,
    description: 'Ganho de massa muscular com superávit controlado para minimizar acúmulo de gordura.',
    active_rules: [
      'Superávit calórico de ~300 kcal',
      'Proteína mínima de 2.0g por kg',
      'Treinar pelo menos 4x por semana',
      'Priorizar treinos compostos',
      'Acompanhar ganho de peso semanal',
    ],
    custom_goals: {
      surplus_kcal: 300,
      training_days_per_week: 4,
      weekly_weight_gain_kg: 0.25,
    },
  },
  {
    id: 'strength_6w',
    name: 'Protocolo de força 6 semanas',
    type: 'strength',
    duration_weeks: 6,
    description: 'Bloco intensivo de força com progressão de carga linear e foco em movimentos compostos.',
    active_rules: [
      'Progressão de carga toda semana',
      'Mínimo 3 treinos de força por semana',
      'Descanso adequado entre séries (2-3 min)',
      'Registrar todos os 1RMs',
      'Proteína mínima de 2.0g por kg',
    ],
    custom_goals: {
      training_days_per_week: 3,
      main_lifts: ['Back Squat', 'Deadlift', 'Bench Press', 'Overhead Press'],
      weekly_pr_attempts: 1,
    },
  },
  {
    id: 'recomp_16w',
    name: 'Recomposição 16 semanas',
    type: 'recomposition',
    duration_weeks: 16,
    description: 'Ciclo longo de recomposição corporal — perder gordura e ganhar músculo ao mesmo tempo.',
    active_rules: [
      'Calorias na manutenção ou leve déficit',
      'Alta ingestão proteica (2.0g/kg)',
      'Treinar 4-5x por semana',
      'Incluir cardio de baixa intensidade',
      'Acompanhar medidas corporais mensalmente',
    ],
    custom_goals: {
      training_days_per_week: 5,
      liss_sessions_per_week: 3,
      measurement_check_weeks: [4, 8, 12, 16],
    },
  },
]

// ─── Predefined Workout Templates ─────────────────────────────────────────────

export const PREDEFINED_WORKOUT_TEMPLATES = [
  {
    id: 'fran',
    name: 'Fran',
    format: 'for_time',
    is_predefined: true,
    description: '21-15-9 Thrusters and Pull-ups — benchmark clássico do CrossFit.',
    structure: {
      rounds: null,
      time_cap_minutes: 10,
      exercises: [
        {
          exercise_id: 'cf_str_thruster',
          name: 'Thruster',
          reps: [21, 15, 9],
          weight_rx: 43,
          weight_rx_f: 29,
          unit: 'kg',
        },
        {
          exercise_id: 'cf_gym_strict_pull_up',
          name: 'Pull-up',
          reps: [21, 15, 9],
          weight_rx: null,
          unit: null,
        },
      ],
    },
  },
  {
    id: 'grace',
    name: 'Grace',
    format: 'for_time',
    is_predefined: true,
    description: '30 Clean & Jerks for time — benchmark de LPO do CrossFit.',
    structure: {
      rounds: null,
      time_cap_minutes: 10,
      exercises: [
        {
          exercise_id: 'cf_oly_clean_and_jerk',
          name: 'Clean and Jerk',
          reps: [30],
          weight_rx: 61,
          weight_rx_f: 43,
          unit: 'kg',
        },
      ],
    },
  },
  {
    id: 'helen',
    name: 'Helen',
    format: 'for_time',
    is_predefined: true,
    description: '3 rounds: 400m run, 21 KB swings, 12 pull-ups.',
    structure: {
      rounds: 3,
      time_cap_minutes: 20,
      exercises: [
        {
          exercise_id: 'cf_mono_running',
          name: 'Running',
          distance_m: 400,
          reps: null,
          weight_rx: null,
          unit: 'm',
        },
        {
          exercise_id: 'func_kettlebell_swing',
          name: 'Kettlebell Swing',
          reps: [21],
          weight_rx: 24,
          weight_rx_f: 16,
          unit: 'kg',
        },
        {
          exercise_id: 'cf_gym_strict_pull_up',
          name: 'Pull-up',
          reps: [12],
          weight_rx: null,
          unit: null,
        },
      ],
    },
  },
  {
    id: 'cindy',
    name: 'Cindy',
    format: 'amrap',
    is_predefined: true,
    description: 'AMRAP 20 min: 5 pull-ups, 10 push-ups, 15 air squats.',
    structure: {
      time_minutes: 20,
      rounds: null,
      exercises: [
        {
          exercise_id: 'cf_gym_strict_pull_up',
          name: 'Pull-up',
          reps: 5,
          weight_rx: null,
          unit: null,
        },
        {
          exercise_id: 'cf_gym_push_up',
          name: 'Push-up',
          reps: 10,
          weight_rx: null,
          unit: null,
        },
        {
          exercise_id: 'cf_gym_air_squat',
          name: 'Air Squat',
          reps: 15,
          weight_rx: null,
          unit: null,
        },
      ],
    },
  },
  {
    id: 'murph',
    name: 'Murph',
    format: 'for_time',
    is_predefined: true,
    description: 'For time: 1mi run, 100 pull-ups, 200 push-ups, 300 air squats, 1mi run. Com colete 9kg.',
    structure: {
      rounds: null,
      time_cap_minutes: 60,
      vest_weight_kg: 9,
      exercises: [
        { exercise_id: 'cf_mono_running',       name: 'Running',    distance_m: 1609, reps: null, unit: 'm',  order: 1 },
        { exercise_id: 'cf_gym_strict_pull_up', name: 'Pull-up',    reps: 100, weight_rx: null, unit: null,   order: 2 },
        { exercise_id: 'cf_gym_push_up',        name: 'Push-up',    reps: 200, weight_rx: null, unit: null,   order: 3 },
        { exercise_id: 'cf_gym_air_squat',      name: 'Air Squat',  reps: 300, weight_rx: null, unit: null,   order: 4 },
        { exercise_id: 'cf_mono_running',       name: 'Running',    distance_m: 1609, reps: null, unit: 'm',  order: 5 },
      ],
    },
  },
  {
    id: 'push_pull_legs',
    name: 'Push/Pull/Legs Básico',
    format: 'strength',
    is_predefined: true,
    description: 'Split clássico de musculação: Empurrar / Puxar / Pernas.',
    structure: {
      days: [
        {
          day_name: 'Push (Peito, Ombros, Tríceps)',
          exercises: [
            { exercise_id: 'wb_chest_supino_reto_barra',             name: 'Supino Reto Barra',             sets: 4, reps: '8-10' },
            { exercise_id: 'wb_chest_supino_inclinado_halteres',     name: 'Supino Inclinado Halteres',     sets: 3, reps: '10-12' },
            { exercise_id: 'wb_shoulders_desenvolvimento_halteres',  name: 'Desenvolvimento Halteres',      sets: 4, reps: '8-10' },
            { exercise_id: 'wb_shoulders_elevacao_lateral_halteres', name: 'Elevação Lateral Halteres',     sets: 3, reps: '12-15' },
            { exercise_id: 'wb_triceps_pulley_corda',                name: 'Tríceps Pulley Corda',          sets: 3, reps: '12-15' },
            { exercise_id: 'wb_triceps_frances_halter',              name: 'Tríceps Francês Halter',        sets: 3, reps: '10-12' },
          ],
        },
        {
          day_name: 'Pull (Costas, Bíceps)',
          exercises: [
            { exercise_id: 'wb_back_puxada_alta_pronada',    name: 'Puxada Alta Pronada',   sets: 4, reps: '8-10' },
            { exercise_id: 'wb_back_remada_curvada_barra',   name: 'Remada Curvada Barra',  sets: 4, reps: '8-10' },
            { exercise_id: 'wb_back_remada_unilateral',      name: 'Remada Unilateral',     sets: 3, reps: '10-12' },
            { exercise_id: 'wb_back_face_pull',              name: 'Face Pull',             sets: 3, reps: '15-20' },
            { exercise_id: 'wb_biceps_rosca_direta_barra_w', name: 'Rosca Direta Barra W',  sets: 3, reps: '10-12' },
            { exercise_id: 'wb_biceps_rosca_martelo',        name: 'Rosca Martelo',         sets: 3, reps: '12-15' },
          ],
        },
        {
          day_name: 'Legs (Pernas, Glúteos)',
          exercises: [
            { exercise_id: 'wb_legs_agachamento_livre',   name: 'Agachamento Livre',     sets: 4, reps: '8-10' },
            { exercise_id: 'wb_legs_leg_press_45',        name: 'Leg Press 45',          sets: 4, reps: '10-12' },
            { exercise_id: 'wb_legs_cadeira_extensora',   name: 'Cadeira Extensora',     sets: 3, reps: '12-15' },
            { exercise_id: 'wb_legs_cadeira_flexora',     name: 'Cadeira Flexora',       sets: 3, reps: '12-15' },
            { exercise_id: 'wb_legs_hip_thrust',          name: 'Hip Thrust',            sets: 4, reps: '10-12' },
            { exercise_id: 'wb_legs_stiff_barra',         name: 'Stiff Barra',           sets: 3, reps: '10-12' },
            { exercise_id: 'wb_calves_gemeos_pe_maquina', name: 'Gêmeos em Pé Máquina', sets: 4, reps: '15-20' },
          ],
        },
      ],
    },
  },
  {
    id: 'hiit_30',
    name: 'Circuito HIIT 30min',
    format: 'custom',
    is_predefined: true,
    description: 'Circuito funcional de alta intensidade com 30 minutos de duração.',
    structure: {
      rounds: 4,
      rest_between_rounds_seconds: 90,
      exercises: [
        { exercise_id: 'cf_gym_burpee',           name: 'Burpee',             duration_seconds: 40, rest_seconds: 20 },
        { exercise_id: 'func_kettlebell_swing',   name: 'Kettlebell Swing',   duration_seconds: 40, rest_seconds: 20, weight_suggestion_kg: 16 },
        { exercise_id: 'cf_gym_air_squat',        name: 'Air Squat',          duration_seconds: 40, rest_seconds: 20 },
        { exercise_id: 'func_medicine_ball_slam', name: 'Medicine Ball Slam', duration_seconds: 40, rest_seconds: 20, weight_suggestion_kg: 6 },
        { exercise_id: 'cf_gym_push_up',          name: 'Push-up',            duration_seconds: 40, rest_seconds: 20 },
        { exercise_id: 'func_battle_rope_waves',  name: 'Battle Rope Waves',  duration_seconds: 40, rest_seconds: 20 },
      ],
    },
  },
]
